### ISSUE TITLE
Access violation occurs at Bsubst

### ISSUE THREAD

**Issue by yuusuke1984** [k-takata/bregonig#1]
bregonig.dll Ver.4.00において、BSubstで検索パターンと検索文字列が完全一致し、置換パターンが空の場合にアクセス違反が起きます。

### 再現方法
python\sample_subst.pyの検索文字列を次のように設定し、
`t1 = "0123".encode('ASCII')`

検索・置換パターンを次のように設定して実行すると、
`pattern1 = r"s/0123//g".encode('ASCII')`

以下のエラーが発生します。
```
$ python 01sample_subst.py
bregonig.dll Ver.4.00 with Onigmo 6.0.0

Traceback (most recent call last):
  File "01sample_subst.py", line 23, in <module>
    print("after(%d)=%s" % (ctr, string_at(rxp.contents.outp).decode('ASCII')))
  File "e:\Programs\Python27-32\lib\ctypes\__init__.py", line 506, in string_at
    return _string_at(ptr, size)
WindowsError: exception: access violation reading 0x00000000
exit status 1
```
### WinDbgに表示されたTRACEの出力
```
BSubst(): 's/0123//g' (038377D4), 038376B4, 038376B4, 038376B8
recompile_onig(): s/0123//g
recompile_onig_ex()
patternp: 0123//g, len: 4
prerepp: /g, len: 0
optionp: g, len: 1
compare_pattern: 0123//g, len: 4compare: -1
option: gcompile_rep()
rx:0x014272e8
subst_onig()
one_shot: 0
one_shot: 0
subst_count: 1
(393c.3080): Access violation - code c0000005 (first chance)
```
### テスト環境
Windows 10 pro（バージョン1607）x64
bregonig.dll Ver.4.00（32bit）
Python 2.7.13（32bit）

報告は以上です。

**Comment by k-takata** [comment]
bregonig.dll ではなく、呼び出し側で NULL ポインタアクセスが起きていました。
どこにも明記されていなかったのですが、BSubst(), BoSubst() で置換した結果が空文字列となった場合、outp には NULL が入ります。これは、bregexp.dll から引き継いでいる挙動です。
BoSubst() の仕様として明記し、サンプルプログラムも NULL チェックを行うように修正しました。

**Comment by yuusuke1984** [comment]
ご回答ありがとうございます。bregexp.dllから引き継いでいる仕様だったのですね。ドキュメントとサンプルプログラムの修正もありがとうございました。
bregonig.dllと鬼雲をさまざまなフリーソフトとともに大変便利に使わせていただいています。ますますのご発展をお祈りしております。
