### ISSUE TITLE
compile error C2248 in sv.cpp with Visual Studio 2017

### ISSUE THREAD

**Issue by dAu6jARL** [k-takata/bregonig#2]
run nmake VS2017 as below.
> nmake ONIG_DIR=../../Onigmo

error C2248 occurred as below.
> sv.cpp(334): error C2248: 'std::bad_alloc::bad_alloc': private メンバー (クラス 'std::bad_alloc' で宣言されている) にアクセスできません。
C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\vcruntime_exception.h(122): note: 'std::bad_alloc::bad_alloc' の宣言を確認してください
C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\vcruntime_exception.h(109): note: 'std::bad_alloc' の宣言を確認してください
sv.cpp(470): error C2248: 'std::bad_alloc::bad_alloc': private メンバー (クラス 'std::bad_alloc' で宣言されている) にアクセスできません。
C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\vcruntime_exception.h(122): note: 'std::bad_alloc::bad_alloc' の宣言を確認してください
C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\vcruntime_exception.h(109): note: 'std::bad_alloc' の宣言を確認してください
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\cl.EXE"' : リターン コード '0x2'

**Comment by k-takata** [comment]
Could you try the latest commit?

**Comment by dAu6jARL** [comment]
Thank you for your rapid response.
I tried the lastest commit rev: 3da1abe3e740f9665c65c9e7b2748edfe8862672.
Sorry, it's a pity that other error occurred in subst.cpp as below.

> subst.cpp
subst.cpp(393): error C2956: サイズ設定された解放関数 'operator delete(void*, size_t)' が仮解放関数として選択されることになります。
h:\misc_huge\workspace\bregonig\src\bregonig.h(74): note: 'ansi::repstr::operator delete' の宣言を確認してください
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX86\x86\cl.EXE"' : リターン コード '0x2'
Stop.

**Comment by k-takata** [comment]
I haven't installed VS2017 yet, but it can reproduce on VS2015.
Please try the latest commit.

**Comment by dAu6jARL** [comment]
success to compile and link rev: 93cdad87f880ea802f7aa1513ba519fd38233a29 .
Thank you.
